stages:
  - build


build.develop:
  stage: build
  before_script:
    - CI_FULL_REGISTRY=bridge-server:develop
  variables:
    NODE_ENV: production
    NODE_APP_INSTANCE: develop
    PORT: 36490
  script:
    - docker build --cache-from $CI_FULL_REGISTRY -t $CI_FULL_REGISTRY .
    - docker-compose -p bridge-develop up -d
  only:
    - develop
    - ECHO-1113
  tags:
    - bridge-dev
  environment:
    name: develop


build.master:
  stage: build
  before_script:
    - CI_FULL_REGISTRY=bridge-server:master
  variables:
    NODE_ENV: production
    NODE_APP_INSTANCE: master
    PORT: 26490
  script:
    - docker build --cache-from $CI_FULL_REGISTRY -t $CI_FULL_REGISTRY .
    - docker-compose -p bridge-master up -d
  only:
    - master
  tags:
    - bridge-dev
  environment:
    name: stage
