stages:
  - test
  - build


test:
  image: node:10.15-alpine
  stage: test
  variables:
    NODE_ENV: test
  cache:
    key: $CI_COMMIT_REF_NAME
    paths:
      - node_modules
  script:
    - npm i
    - npm run lint
  tags:
    - docker
  only:
    - merge_requests
    - develop
    - master


build.develop:
  stage: build
  before_script:
    - CI_FULL_REGISTRY=bridge-server:develop
  variables:
    NODE_ENV: production
    NODE_APP_INSTANCE: develop
  script:
    - docker build --cache-from $CI_FULL_REGISTRY -t $CI_FULL_REGISTRY .
    - docker-compose -p bridge-develop up -d
  only:
    - develop
  tags:
    - pp-develop
  environment:
    name: develop


build.master:
  stage: build
  variables:
    NODE_ENV: production
    NODE_APP_INSTANCE: master
    EXPORT_HOST_DB: 127.0.0.1
  script:
    - docker build -t 649.bridge.server.api . --no-cache
    - docker-compose down
    - docker-compose up -d
  only:
    - master
  tags:
    - pp-stage
  environment:
    name: master
