version: '3'

services:

  bridge.backend.api:
    image: $CI_FULL_REGISTRY
    environment:
      - NODE_ENV=production
      - NODE_APP_INSTANCE=$NODE_APP_INSTANCE
    ports:
      - 127.0.0.1:${PORT}:3000
    restart: always
