apiVersion: apps/v1
kind: Deployment
metadata:
  name: bridge-server
spec:
  replicas: 2
  minReadySeconds: 15
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: bridge
    spec:
      containers:
        - image: echoprotocol/bridge-server:latest
          imagePullPolicy: Always
          name: bridge-server
          env:
            - name: NODE_ENV
              value: production
            - name: NODE_APP_INSTANCE
              value: production
          ports:
            - containerPort: 3000

---

apiVersion: v1
kind: Service
metadata:
  name: dridge-lb
spec:
  type: LoadBalancer
  ports:
  - port: 26490
    protocol: TCP
    targetPort: 3000
  selector:
    app: bridge
